<?php
/**
 * AusbildungsgangTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * VEDA Bildungsmanager API
 *
 * Dokumentation der REST-Schnittstellen des VEDA Bildungsmanagers für die Version 2. Die Dokumentation zu speziellen Versionen kann über die Angabe des zusätzlichen Parameters \"group\" angezeigt werden. Beispiel: .../api/docs?group=v1 für die Dokumentation der Version 1, die aktuelle Version ist unter .../api/docs erreichbar.
 *
 * OpenAPI spec version: 2
 * Contact: info@veda.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AusbildungsgangTest Class Doc Comment
 *
 * @category    Class
 * @description Ausbildungsgang mit den sortierten Ausbildungsgangabschnitten.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AusbildungsgangTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Ausbildungsgang"
     */
    public function testAusbildungsgang()
    {
    }

    /**
     * Test attribute "oid"
     */
    public function testPropertyOid()
    {
    }

    /**
     * Test attribute "ausbildungsgangabschnitte"
     */
    public function testPropertyAusbildungsgangabschnitte()
    {
    }

    /**
     * Test attribute "bezeichnung"
     */
    public function testPropertyBezeichnung()
    {
    }

    /**
     * Test attribute "kurzbezeichnung"
     */
    public function testPropertyKurzbezeichnung()
    {
    }

    /**
     * Test attribute "links"
     */
    public function testPropertyLinks()
    {
    }
}
