<?php
/**
 * VeranstaltungsterminTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * VEDA Bildungsmanager API
 *
 * Dokumentation der REST-Schnittstellen des VEDA Bildungsmanagers für die Version 2. Die Dokumentation zu speziellen Versionen kann über die Angabe des zusätzlichen Parameters \"group\" angezeigt werden. Beispiel: .../api/docs?group=v1 für die Dokumentation der Version 1, die aktuelle Version ist unter .../api/docs erreichbar.
 *
 * OpenAPI spec version: 2
 * Contact: info@veda.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * VeranstaltungsterminTest Class Doc Comment
 *
 * @category    Class
 * @description Ein Veranstaltungstermin mit seinen relevanten Daten
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class VeranstaltungsterminTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Veranstaltungstermin"
     */
    public function testVeranstaltungstermin()
    {
    }

    /**
     * Test attribute "oid"
     */
    public function testPropertyOid()
    {
    }

    /**
     * Test attribute "anz_teilnehmertage_pro_teilnehmer"
     */
    public function testPropertyAnzTeilnehmertageProTeilnehmer()
    {
    }

    /**
     * Test attribute "anzahl_freier_plaetze"
     */
    public function testPropertyAnzahlFreierPlaetze()
    {
    }

    /**
     * Test attribute "anzahl_freier_wartelistenplaetze"
     */
    public function testPropertyAnzahlFreierWartelistenplaetze()
    {
    }

    /**
     * Test attribute "anzahl_teilnehmerbuchungen"
     */
    public function testPropertyAnzahlTeilnehmerbuchungen()
    {
    }

    /**
     * Test attribute "anzahl_ue"
     */
    public function testPropertyAnzahlUe()
    {
    }

    /**
     * Test attribute "anzahl_wartelistenbuchungen"
     */
    public function testPropertyAnzahlWartelistenbuchungen()
    {
    }

    /**
     * Test attribute "auslastungsstatus"
     */
    public function testPropertyAuslastungsstatus()
    {
    }

    /**
     * Test attribute "beschreibung"
     */
    public function testPropertyBeschreibung()
    {
    }

    /**
     * Test attribute "dauer_in_tagen"
     */
    public function testPropertyDauerInTagen()
    {
    }

    /**
     * Test attribute "hinweise"
     */
    public function testPropertyHinweise()
    {
    }

    /**
     * Test attribute "inhalt"
     */
    public function testPropertyInhalt()
    {
    }

    /**
     * Test attribute "links"
     */
    public function testPropertyLinks()
    {
    }

    /**
     * Test attribute "methodik"
     */
    public function testPropertyMethodik()
    {
    }

    /**
     * Test attribute "preis"
     */
    public function testPropertyPreis()
    {
    }

    /**
     * Test attribute "preise_je_teilnehmergruppe"
     */
    public function testPropertyPreiseJeTeilnehmergruppe()
    {
    }

    /**
     * Test attribute "reg_uhrzeit_bis"
     */
    public function testPropertyRegUhrzeitBis()
    {
    }

    /**
     * Test attribute "reg_uhrzeit_von"
     */
    public function testPropertyRegUhrzeitVon()
    {
    }

    /**
     * Test attribute "sprache"
     */
    public function testPropertySprache()
    {
    }

    /**
     * Test attribute "teilnehmermaximum"
     */
    public function testPropertyTeilnehmermaximum()
    {
    }

    /**
     * Test attribute "teilnehmerminimum"
     */
    public function testPropertyTeilnehmerminimum()
    {
    }

    /**
     * Test attribute "termin_bis"
     */
    public function testPropertyTerminBis()
    {
    }

    /**
     * Test attribute "termin_von"
     */
    public function testPropertyTerminVon()
    {
    }

    /**
     * Test attribute "thema"
     */
    public function testPropertyThema()
    {
    }

    /**
     * Test attribute "thema2"
     */
    public function testPropertyThema2()
    {
    }

    /**
     * Test attribute "veranstaltungs_nr"
     */
    public function testPropertyVeranstaltungsNr()
    {
    }

    /**
     * Test attribute "veranstaltungsanbieter"
     */
    public function testPropertyVeranstaltungsanbieter()
    {
    }

    /**
     * Test attribute "veranstaltungsart"
     */
    public function testPropertyVeranstaltungsart()
    {
    }

    /**
     * Test attribute "veranstaltungskategorie"
     */
    public function testPropertyVeranstaltungskategorie()
    {
    }

    /**
     * Test attribute "veranstaltungsort"
     */
    public function testPropertyVeranstaltungsort()
    {
    }

    /**
     * Test attribute "veranstaltungstyp_id"
     */
    public function testPropertyVeranstaltungstypId()
    {
    }

    /**
     * Test attribute "voraussetzung"
     */
    public function testPropertyVoraussetzung()
    {
    }

    /**
     * Test attribute "wartelistenmaximum"
     */
    public function testPropertyWartelistenmaximum()
    {
    }

    /**
     * Test attribute "wbd_relevant"
     */
    public function testPropertyWbdRelevant()
    {
    }

    /**
     * Test attribute "wbd_thema"
     */
    public function testPropertyWbdThema()
    {
    }

    /**
     * Test attribute "ziel"
     */
    public function testPropertyZiel()
    {
    }

    /**
     * Test attribute "zielgruppen"
     */
    public function testPropertyZielgruppen()
    {
    }
}
