<?php
/**
 * WebBasedTrainingTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * VEDA Bildungsmanager API
 *
 * Dokumentation der REST-Schnittstellen des VEDA Bildungsmanagers für die Version 2. Die Dokumentation zu speziellen Versionen kann über die Angabe des zusätzlichen Parameters \"group\" angezeigt werden. Beispiel: .../api/docs?group=v1 für die Dokumentation der Version 1, die aktuelle Version ist unter .../api/docs erreichbar.
 *
 * OpenAPI spec version: 2
 * Contact: info@veda.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * WebBasedTrainingTest Class Doc Comment
 *
 * @category    Class
 * @description Ein Web Based Training mit seinen relevanten Daten.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class WebBasedTrainingTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "WebBasedTraining"
     */
    public function testWebBasedTraining()
    {
    }

    /**
     * Test attribute "oid"
     */
    public function testPropertyOid()
    {
    }

    /**
     * Test attribute "anzahl_ue"
     */
    public function testPropertyAnzahlUe()
    {
    }

    /**
     * Test attribute "beschreibung"
     */
    public function testPropertyBeschreibung()
    {
    }

    /**
     * Test attribute "gueltig_ab"
     */
    public function testPropertyGueltigAb()
    {
    }

    /**
     * Test attribute "gueltig_bis"
     */
    public function testPropertyGueltigBis()
    {
    }

    /**
     * Test attribute "hinweise"
     */
    public function testPropertyHinweise()
    {
    }

    /**
     * Test attribute "inhalt"
     */
    public function testPropertyInhalt()
    {
    }

    /**
     * Test attribute "kurzbezeichnung"
     */
    public function testPropertyKurzbezeichnung()
    {
    }

    /**
     * Test attribute "links"
     */
    public function testPropertyLinks()
    {
    }

    /**
     * Test attribute "methodik"
     */
    public function testPropertyMethodik()
    {
    }

    /**
     * Test attribute "thema"
     */
    public function testPropertyThema()
    {
    }

    /**
     * Test attribute "thema2"
     */
    public function testPropertyThema2()
    {
    }

    /**
     * Test attribute "veranstaltungs_nr"
     */
    public function testPropertyVeranstaltungsNr()
    {
    }

    /**
     * Test attribute "voraussetzung"
     */
    public function testPropertyVoraussetzung()
    {
    }

    /**
     * Test attribute "wbd_relevant"
     */
    public function testPropertyWbdRelevant()
    {
    }

    /**
     * Test attribute "wbd_thema"
     */
    public function testPropertyWbdThema()
    {
    }

    /**
     * Test attribute "ziel"
     */
    public function testPropertyZiel()
    {
    }

    /**
     * Test attribute "zielgruppen_i_ds"
     */
    public function testPropertyZielgruppenIDs()
    {
    }
}
