<?php
/**
 * ELearningPlattformenApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * VEDA Bildungsmanager API
 *
 * Dokumentation der REST-Schnittstellen des VEDA Bildungsmanagers für die Version 2. Die Dokumentation zu speziellen Versionen kann über die Angabe des zusätzlichen Parameters \"group\" angezeigt werden. Beispiel: .../api/docs?group=v1 für die Dokumentation der Version 1, die aktuelle Version ist unter .../api/docs erreichbar.
 *
 * OpenAPI spec version: 2
 * Contact: info@veda.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.10
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Swagger\Client\ApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * ELearningPlattformenApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ELearningPlattformenApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getFreigegebeneAusbildungszuegeFuerPlattformUndAusbildungsgangUsingGET
     *
     * Ruft alle Ausbildungszüge eines Ausbildungsgangs ab, die zur E-Learning-Plattform gehören
     *
     * @param  string $plattform_id ID der E-Learning-Plattform (required)
     * @param  string $ausbildungsgang_id ID des Ausbildungsgangs (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\Ausbildungszug[]
     */
    public function getFreigegebeneAusbildungszuegeFuerPlattformUndAusbildungsgangUsingGET($plattform_id, $ausbildungsgang_id)
    {
        list($response) = $this->getFreigegebeneAusbildungszuegeFuerPlattformUndAusbildungsgangUsingGETWithHttpInfo($plattform_id, $ausbildungsgang_id);
        return $response;
    }

    /**
     * Operation getFreigegebeneAusbildungszuegeFuerPlattformUndAusbildungsgangUsingGETWithHttpInfo
     *
     * Ruft alle Ausbildungszüge eines Ausbildungsgangs ab, die zur E-Learning-Plattform gehören
     *
     * @param  string $plattform_id ID der E-Learning-Plattform (required)
     * @param  string $ausbildungsgang_id ID des Ausbildungsgangs (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\Ausbildungszug[], HTTP status code, HTTP response headers (array of strings)
     */
    public function getFreigegebeneAusbildungszuegeFuerPlattformUndAusbildungsgangUsingGETWithHttpInfo($plattform_id, $ausbildungsgang_id)
    {
        $returnType = '\Swagger\Client\Model\Ausbildungszug[]';
        $request = $this->getFreigegebeneAusbildungszuegeFuerPlattformUndAusbildungsgangUsingGETRequest($plattform_id, $ausbildungsgang_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Ausbildungszug[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getFreigegebeneAusbildungszuegeFuerPlattformUndAusbildungsgangUsingGETAsync
     *
     * Ruft alle Ausbildungszüge eines Ausbildungsgangs ab, die zur E-Learning-Plattform gehören
     *
     * @param  string $plattform_id ID der E-Learning-Plattform (required)
     * @param  string $ausbildungsgang_id ID des Ausbildungsgangs (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getFreigegebeneAusbildungszuegeFuerPlattformUndAusbildungsgangUsingGETAsync($plattform_id, $ausbildungsgang_id)
    {
        return $this->getFreigegebeneAusbildungszuegeFuerPlattformUndAusbildungsgangUsingGETAsyncWithHttpInfo($plattform_id, $ausbildungsgang_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getFreigegebeneAusbildungszuegeFuerPlattformUndAusbildungsgangUsingGETAsyncWithHttpInfo
     *
     * Ruft alle Ausbildungszüge eines Ausbildungsgangs ab, die zur E-Learning-Plattform gehören
     *
     * @param  string $plattform_id ID der E-Learning-Plattform (required)
     * @param  string $ausbildungsgang_id ID des Ausbildungsgangs (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getFreigegebeneAusbildungszuegeFuerPlattformUndAusbildungsgangUsingGETAsyncWithHttpInfo($plattform_id, $ausbildungsgang_id)
    {
        $returnType = '\Swagger\Client\Model\Ausbildungszug[]';
        $request = $this->getFreigegebeneAusbildungszuegeFuerPlattformUndAusbildungsgangUsingGETRequest($plattform_id, $ausbildungsgang_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getFreigegebeneAusbildungszuegeFuerPlattformUndAusbildungsgangUsingGET'
     *
     * @param  string $plattform_id ID der E-Learning-Plattform (required)
     * @param  string $ausbildungsgang_id ID des Ausbildungsgangs (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getFreigegebeneAusbildungszuegeFuerPlattformUndAusbildungsgangUsingGETRequest($plattform_id, $ausbildungsgang_id)
    {
        // verify the required parameter 'plattform_id' is set
        if ($plattform_id === null || (is_array($plattform_id) && count($plattform_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $plattform_id when calling getFreigegebeneAusbildungszuegeFuerPlattformUndAusbildungsgangUsingGET'
            );
        }
        // verify the required parameter 'ausbildungsgang_id' is set
        if ($ausbildungsgang_id === null || (is_array($ausbildungsgang_id) && count($ausbildungsgang_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ausbildungsgang_id when calling getFreigegebeneAusbildungszuegeFuerPlattformUndAusbildungsgangUsingGET'
            );
        }

        $resourcePath = '/v2/elearningplattformen/{plattformId}/ausbildungszuege';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($ausbildungsgang_id !== null) {
            $queryParams['ausbildungsgangId'] = ObjectSerializer::toQueryValue($ausbildungsgang_id);
        }

        // path params
        if ($plattform_id !== null) {
            $resourcePath = str_replace(
                '{' . 'plattformId' . '}',
                ObjectSerializer::toPathValue($plattform_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getTeilnehmerELearningPlattformUsingGET
     *
     * Ruft alle Teilnehmer einer E-Learning-Plattform ab
     *
     * @param  string $plattform_id ID der E-Learning-Plattform (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\TeilnehmerELearningPlattform[]
     */
    public function getTeilnehmerELearningPlattformUsingGET($plattform_id)
    {
        list($response) = $this->getTeilnehmerELearningPlattformUsingGETWithHttpInfo($plattform_id);
        return $response;
    }

    /**
     * Operation getTeilnehmerELearningPlattformUsingGETWithHttpInfo
     *
     * Ruft alle Teilnehmer einer E-Learning-Plattform ab
     *
     * @param  string $plattform_id ID der E-Learning-Plattform (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\TeilnehmerELearningPlattform[], HTTP status code, HTTP response headers (array of strings)
     */
    public function getTeilnehmerELearningPlattformUsingGETWithHttpInfo($plattform_id)
    {
        $returnType = '\Swagger\Client\Model\TeilnehmerELearningPlattform[]';
        $request = $this->getTeilnehmerELearningPlattformUsingGETRequest($plattform_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\TeilnehmerELearningPlattform[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getTeilnehmerELearningPlattformUsingGETAsync
     *
     * Ruft alle Teilnehmer einer E-Learning-Plattform ab
     *
     * @param  string $plattform_id ID der E-Learning-Plattform (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getTeilnehmerELearningPlattformUsingGETAsync($plattform_id)
    {
        return $this->getTeilnehmerELearningPlattformUsingGETAsyncWithHttpInfo($plattform_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getTeilnehmerELearningPlattformUsingGETAsyncWithHttpInfo
     *
     * Ruft alle Teilnehmer einer E-Learning-Plattform ab
     *
     * @param  string $plattform_id ID der E-Learning-Plattform (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getTeilnehmerELearningPlattformUsingGETAsyncWithHttpInfo($plattform_id)
    {
        $returnType = '\Swagger\Client\Model\TeilnehmerELearningPlattform[]';
        $request = $this->getTeilnehmerELearningPlattformUsingGETRequest($plattform_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getTeilnehmerELearningPlattformUsingGET'
     *
     * @param  string $plattform_id ID der E-Learning-Plattform (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getTeilnehmerELearningPlattformUsingGETRequest($plattform_id)
    {
        // verify the required parameter 'plattform_id' is set
        if ($plattform_id === null || (is_array($plattform_id) && count($plattform_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $plattform_id when calling getTeilnehmerELearningPlattformUsingGET'
            );
        }

        $resourcePath = '/v2/elearningplattformen/{plattformId}/teilnehmer';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($plattform_id !== null) {
            $resourcePath = str_replace(
                '{' . 'plattformId' . '}',
                ObjectSerializer::toPathValue($plattform_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation meldeElearningaccountAlsExternExistierendUsingPOST
     *
     * Meldet, dass der Benutzer auf der externen E-Learning-Plattform existiert
     *
     * @param  string $plattform_id ID der E-Learning-Plattform (required)
     * @param  string $teilnehmer_id ID des Teilnehmers (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function meldeElearningaccountAlsExternExistierendUsingPOST($plattform_id, $teilnehmer_id)
    {
        $this->meldeElearningaccountAlsExternExistierendUsingPOSTWithHttpInfo($plattform_id, $teilnehmer_id);
    }

    /**
     * Operation meldeElearningaccountAlsExternExistierendUsingPOSTWithHttpInfo
     *
     * Meldet, dass der Benutzer auf der externen E-Learning-Plattform existiert
     *
     * @param  string $plattform_id ID der E-Learning-Plattform (required)
     * @param  string $teilnehmer_id ID des Teilnehmers (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function meldeElearningaccountAlsExternExistierendUsingPOSTWithHttpInfo($plattform_id, $teilnehmer_id)
    {
        $returnType = '';
        $request = $this->meldeElearningaccountAlsExternExistierendUsingPOSTRequest($plattform_id, $teilnehmer_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation meldeElearningaccountAlsExternExistierendUsingPOSTAsync
     *
     * Meldet, dass der Benutzer auf der externen E-Learning-Plattform existiert
     *
     * @param  string $plattform_id ID der E-Learning-Plattform (required)
     * @param  string $teilnehmer_id ID des Teilnehmers (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function meldeElearningaccountAlsExternExistierendUsingPOSTAsync($plattform_id, $teilnehmer_id)
    {
        return $this->meldeElearningaccountAlsExternExistierendUsingPOSTAsyncWithHttpInfo($plattform_id, $teilnehmer_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation meldeElearningaccountAlsExternExistierendUsingPOSTAsyncWithHttpInfo
     *
     * Meldet, dass der Benutzer auf der externen E-Learning-Plattform existiert
     *
     * @param  string $plattform_id ID der E-Learning-Plattform (required)
     * @param  string $teilnehmer_id ID des Teilnehmers (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function meldeElearningaccountAlsExternExistierendUsingPOSTAsyncWithHttpInfo($plattform_id, $teilnehmer_id)
    {
        $returnType = '';
        $request = $this->meldeElearningaccountAlsExternExistierendUsingPOSTRequest($plattform_id, $teilnehmer_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'meldeElearningaccountAlsExternExistierendUsingPOST'
     *
     * @param  string $plattform_id ID der E-Learning-Plattform (required)
     * @param  string $teilnehmer_id ID des Teilnehmers (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function meldeElearningaccountAlsExternExistierendUsingPOSTRequest($plattform_id, $teilnehmer_id)
    {
        // verify the required parameter 'plattform_id' is set
        if ($plattform_id === null || (is_array($plattform_id) && count($plattform_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $plattform_id when calling meldeElearningaccountAlsExternExistierendUsingPOST'
            );
        }
        // verify the required parameter 'teilnehmer_id' is set
        if ($teilnehmer_id === null || (is_array($teilnehmer_id) && count($teilnehmer_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $teilnehmer_id when calling meldeElearningaccountAlsExternExistierendUsingPOST'
            );
        }

        $resourcePath = '/v2/elearningplattformen/{plattformId}/teilnehmer/{teilnehmerId}/meldeexternexistierend';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($plattform_id !== null) {
            $resourcePath = str_replace(
                '{' . 'plattformId' . '}',
                ObjectSerializer::toPathValue($plattform_id),
                $resourcePath
            );
        }
        // path params
        if ($teilnehmer_id !== null) {
            $resourcePath = str_replace(
                '{' . 'teilnehmerId' . '}',
                ObjectSerializer::toPathValue($teilnehmer_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['*/*']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['*/*'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation meldeErstmaligErfolgreichEingeloggtUsingPOST
     *
     * Setzt das Datum für das Ändern des initialen Passworts
     *
     * @param  string $plattform_id ID der E-Learning-Plattform (required)
     * @param  string $teilnehmer_id ID des Teilnehmers (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function meldeErstmaligErfolgreichEingeloggtUsingPOST($plattform_id, $teilnehmer_id)
    {
        $this->meldeErstmaligErfolgreichEingeloggtUsingPOSTWithHttpInfo($plattform_id, $teilnehmer_id);
    }

    /**
     * Operation meldeErstmaligErfolgreichEingeloggtUsingPOSTWithHttpInfo
     *
     * Setzt das Datum für das Ändern des initialen Passworts
     *
     * @param  string $plattform_id ID der E-Learning-Plattform (required)
     * @param  string $teilnehmer_id ID des Teilnehmers (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function meldeErstmaligErfolgreichEingeloggtUsingPOSTWithHttpInfo($plattform_id, $teilnehmer_id)
    {
        $returnType = '';
        $request = $this->meldeErstmaligErfolgreichEingeloggtUsingPOSTRequest($plattform_id, $teilnehmer_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation meldeErstmaligErfolgreichEingeloggtUsingPOSTAsync
     *
     * Setzt das Datum für das Ändern des initialen Passworts
     *
     * @param  string $plattform_id ID der E-Learning-Plattform (required)
     * @param  string $teilnehmer_id ID des Teilnehmers (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function meldeErstmaligErfolgreichEingeloggtUsingPOSTAsync($plattform_id, $teilnehmer_id)
    {
        return $this->meldeErstmaligErfolgreichEingeloggtUsingPOSTAsyncWithHttpInfo($plattform_id, $teilnehmer_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation meldeErstmaligErfolgreichEingeloggtUsingPOSTAsyncWithHttpInfo
     *
     * Setzt das Datum für das Ändern des initialen Passworts
     *
     * @param  string $plattform_id ID der E-Learning-Plattform (required)
     * @param  string $teilnehmer_id ID des Teilnehmers (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function meldeErstmaligErfolgreichEingeloggtUsingPOSTAsyncWithHttpInfo($plattform_id, $teilnehmer_id)
    {
        $returnType = '';
        $request = $this->meldeErstmaligErfolgreichEingeloggtUsingPOSTRequest($plattform_id, $teilnehmer_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'meldeErstmaligErfolgreichEingeloggtUsingPOST'
     *
     * @param  string $plattform_id ID der E-Learning-Plattform (required)
     * @param  string $teilnehmer_id ID des Teilnehmers (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function meldeErstmaligErfolgreichEingeloggtUsingPOSTRequest($plattform_id, $teilnehmer_id)
    {
        // verify the required parameter 'plattform_id' is set
        if ($plattform_id === null || (is_array($plattform_id) && count($plattform_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $plattform_id when calling meldeErstmaligErfolgreichEingeloggtUsingPOST'
            );
        }
        // verify the required parameter 'teilnehmer_id' is set
        if ($teilnehmer_id === null || (is_array($teilnehmer_id) && count($teilnehmer_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $teilnehmer_id when calling meldeErstmaligErfolgreichEingeloggtUsingPOST'
            );
        }

        $resourcePath = '/v2/elearningplattformen/{plattformId}/teilnehmer/{teilnehmerId}/meldeinitialespasswortgeaendert';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($plattform_id !== null) {
            $resourcePath = str_replace(
                '{' . 'plattformId' . '}',
                ObjectSerializer::toPathValue($plattform_id),
                $resourcePath
            );
        }
        // path params
        if ($teilnehmer_id !== null) {
            $resourcePath = str_replace(
                '{' . 'teilnehmerId' . '}',
                ObjectSerializer::toPathValue($teilnehmer_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['*/*']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['*/*'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
