<?php
/**
 * Ausbildungsabschnitt
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * VEDA Bildungsmanager API
 *
 * Dokumentation der REST-Schnittstellen des VEDA Bildungsmanagers für die Version 2. Die Dokumentation zu speziellen Versionen kann über die Angabe des zusätzlichen Parameters \"group\" angezeigt werden. Beispiel: .../api/docs?group=v1 für die Dokumentation der Version 1, die aktuelle Version ist unter .../api/docs erreichbar.
 *
 * OpenAPI spec version: 2
 * Contact: info@veda.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * Ausbildungsabschnitt Class Doc Comment
 *
 * @category Class
 * @description Ein Abschnitt einer Ausbildung.
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Ausbildungsabschnitt implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Ausbildungsabschnitt';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'oid' => 'string',
        'ausbildungszug_id' => 'string',
        'ausbildungszugabschnitt_id' => 'string',
        'datum_lernerfolg' => '\DateTime',
        'lernerfolg' => 'bool',
        'links' => '\Swagger\Client\Model\Link[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'oid' => null,
        'ausbildungszug_id' => null,
        'ausbildungszugabschnitt_id' => null,
        'datum_lernerfolg' => 'date',
        'lernerfolg' => null,
        'links' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'oid' => 'oid',
        'ausbildungszug_id' => 'ausbildungszugId',
        'ausbildungszugabschnitt_id' => 'ausbildungszugabschnittId',
        'datum_lernerfolg' => 'datumLernerfolg',
        'lernerfolg' => 'lernerfolg',
        'links' => 'links'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'oid' => 'setOid',
        'ausbildungszug_id' => 'setAusbildungszugId',
        'ausbildungszugabschnitt_id' => 'setAusbildungszugabschnittId',
        'datum_lernerfolg' => 'setDatumLernerfolg',
        'lernerfolg' => 'setLernerfolg',
        'links' => 'setLinks'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'oid' => 'getOid',
        'ausbildungszug_id' => 'getAusbildungszugId',
        'ausbildungszugabschnitt_id' => 'getAusbildungszugabschnittId',
        'datum_lernerfolg' => 'getDatumLernerfolg',
        'lernerfolg' => 'getLernerfolg',
        'links' => 'getLinks'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['oid'] = isset($data['oid']) ? $data['oid'] : null;
        $this->container['ausbildungszug_id'] = isset($data['ausbildungszug_id']) ? $data['ausbildungszug_id'] : null;
        $this->container['ausbildungszugabschnitt_id'] = isset($data['ausbildungszugabschnitt_id']) ? $data['ausbildungszugabschnitt_id'] : null;
        $this->container['datum_lernerfolg'] = isset($data['datum_lernerfolg']) ? $data['datum_lernerfolg'] : null;
        $this->container['lernerfolg'] = isset($data['lernerfolg']) ? $data['lernerfolg'] : null;
        $this->container['links'] = isset($data['links']) ? $data['links'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['oid'] === null) {
            $invalidProperties[] = "'oid' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets oid
     *
     * @return string
     */
    public function getOid()
    {
        return $this->container['oid'];
    }

    /**
     * Sets oid
     *
     * @param string $oid UUID des Datensatzes
     *
     * @return $this
     */
    public function setOid($oid)
    {
        $this->container['oid'] = $oid;

        return $this;
    }

    /**
     * Gets ausbildungszug_id
     *
     * @return string
     */
    public function getAusbildungszugId()
    {
        return $this->container['ausbildungszug_id'];
    }

    /**
     * Sets ausbildungszug_id
     *
     * @param string $ausbildungszug_id ID des Ausbildungszugs des Abschnitts. Der Ausbildungszug kann von dem Haupt-Ausbildungszug der Ausbildung abweichen.
     *
     * @return $this
     */
    public function setAusbildungszugId($ausbildungszug_id)
    {
        $this->container['ausbildungszug_id'] = $ausbildungszug_id;

        return $this;
    }

    /**
     * Gets ausbildungszugabschnitt_id
     *
     * @return string
     */
    public function getAusbildungszugabschnittId()
    {
        return $this->container['ausbildungszugabschnitt_id'];
    }

    /**
     * Sets ausbildungszugabschnitt_id
     *
     * @param string $ausbildungszugabschnitt_id ID des Ausbildungszugabschnitts
     *
     * @return $this
     */
    public function setAusbildungszugabschnittId($ausbildungszugabschnitt_id)
    {
        $this->container['ausbildungszugabschnitt_id'] = $ausbildungszugabschnitt_id;

        return $this;
    }

    /**
     * Gets datum_lernerfolg
     *
     * @return \DateTime
     */
    public function getDatumLernerfolg()
    {
        return $this->container['datum_lernerfolg'];
    }

    /**
     * Sets datum_lernerfolg
     *
     * @param \DateTime $datum_lernerfolg Datum des Lernerfolgs
     *
     * @return $this
     */
    public function setDatumLernerfolg($datum_lernerfolg)
    {
        $this->container['datum_lernerfolg'] = $datum_lernerfolg;

        return $this;
    }

    /**
     * Gets lernerfolg
     *
     * @return bool
     */
    public function getLernerfolg()
    {
        return $this->container['lernerfolg'];
    }

    /**
     * Sets lernerfolg
     *
     * @param bool $lernerfolg Lernerfolg des Abschnitts
     *
     * @return $this
     */
    public function setLernerfolg($lernerfolg)
    {
        $this->container['lernerfolg'] = $lernerfolg;

        return $this;
    }

    /**
     * Gets links
     *
     * @return \Swagger\Client\Model\Link[]
     */
    public function getLinks()
    {
        return $this->container['links'];
    }

    /**
     * Sets links
     *
     * @param \Swagger\Client\Model\Link[] $links links
     *
     * @return $this
     */
    public function setLinks($links)
    {
        $this->container['links'] = $links;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


