<?php
/**
 * TeilnehmerELearningplattform
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * VEDA Bildungsmanager API
 *
 * REST-Schnittstellen des VEDA Bildungsmanagers.
 *
 * OpenAPI spec version: 1
 * Contact: info@veda.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.5
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * TeilnehmerELearningplattform Class Doc Comment
 *
 * @category Class
 * @description Teilnehmer einer eLearning-Plattform mit relevanten Informationen.
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TeilnehmerELearningplattform implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'TeilnehmerELearningplattform';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'elearning_plattform_id' => 'string',
        'initiales_passwort' => 'string',
        'links' => '\Swagger\Client\Model\Link[]',
        'teilnehmer' => '\Swagger\Client\Model\Teilnehmer'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'elearning_plattform_id' => null,
        'initiales_passwort' => null,
        'links' => null,
        'teilnehmer' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'elearning_plattform_id' => 'elearningPlattformId',
        'initiales_passwort' => 'initialesPasswort',
        'links' => 'links',
        'teilnehmer' => 'teilnehmer'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'elearning_plattform_id' => 'setElearningPlattformId',
        'initiales_passwort' => 'setInitialesPasswort',
        'links' => 'setLinks',
        'teilnehmer' => 'setTeilnehmer'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'elearning_plattform_id' => 'getElearningPlattformId',
        'initiales_passwort' => 'getInitialesPasswort',
        'links' => 'getLinks',
        'teilnehmer' => 'getTeilnehmer'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['elearning_plattform_id'] = isset($data['elearning_plattform_id']) ? $data['elearning_plattform_id'] : null;
        $this->container['initiales_passwort'] = isset($data['initiales_passwort']) ? $data['initiales_passwort'] : null;
        $this->container['links'] = isset($data['links']) ? $data['links'] : null;
        $this->container['teilnehmer'] = isset($data['teilnehmer']) ? $data['teilnehmer'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['teilnehmer'] === null) {
            $invalidProperties[] = "'teilnehmer' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets elearning_plattform_id
     *
     * @return string
     */
    public function getElearningPlattformId()
    {
        return $this->container['elearning_plattform_id'];
    }

    /**
     * Sets elearning_plattform_id
     *
     * @param string $elearning_plattform_id elearning_plattform_id
     *
     * @return $this
     */
    public function setElearningPlattformId($elearning_plattform_id)
    {
        $this->container['elearning_plattform_id'] = $elearning_plattform_id;

        return $this;
    }

    /**
     * Gets initiales_passwort
     *
     * @return string
     */
    public function getInitialesPasswort()
    {
        return $this->container['initiales_passwort'];
    }

    /**
     * Sets initiales_passwort
     *
     * @param string $initiales_passwort Das initiale Passwort für die eLearning-Plattform
     *
     * @return $this
     */
    public function setInitialesPasswort($initiales_passwort)
    {
        $this->container['initiales_passwort'] = $initiales_passwort;

        return $this;
    }

    /**
     * Gets links
     *
     * @return \Swagger\Client\Model\Link[]
     */
    public function getLinks()
    {
        return $this->container['links'];
    }

    /**
     * Sets links
     *
     * @param \Swagger\Client\Model\Link[] $links links
     *
     * @return $this
     */
    public function setLinks($links)
    {
        $this->container['links'] = $links;

        return $this;
    }

    /**
     * Gets teilnehmer
     *
     * @return \Swagger\Client\Model\Teilnehmer
     */
    public function getTeilnehmer()
    {
        return $this->container['teilnehmer'];
    }

    /**
     * Sets teilnehmer
     *
     * @param \Swagger\Client\Model\Teilnehmer $teilnehmer Teilnehmer der eLearning-Plattform
     *
     * @return $this
     */
    public function setTeilnehmer($teilnehmer)
    {
        $this->container['teilnehmer'] = $teilnehmer;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


