<?php
/**
 * TeilnehmerAktionStornierenApiDto
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * VEDA Bildungsmanager API
 *
 * Dokumentation der REST-Schnittstellen des VEDA Bildungsmanagers für die Version 2. Die Dokumentation zu speziellen Versionen kann über die Angabe des zusätzlichen Parameters \"group\" angezeigt werden. Beispiel: .../api/docs?group=v1 für die Dokumentation der Version 1, die aktuelle Version ist unter .../api/docs erreichbar.
 *
 * OpenAPI spec version: 2
 * Contact: info@veda.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.9
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * TeilnehmerAktionStornierenApiDto Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TeilnehmerAktionStornierenApiDto implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'TeilnehmerAktionStornierenApiDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'kuerzel_stornierungs_grund' => 'string',
        'links' => '\Swagger\Client\Model\Link[]',
        'stornierungsdatum_fremdsystem' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'kuerzel_stornierungs_grund' => null,
        'links' => null,
        'stornierungsdatum_fremdsystem' => 'date'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'kuerzel_stornierungs_grund' => 'kuerzelStornierungsGrund',
        'links' => 'links',
        'stornierungsdatum_fremdsystem' => 'stornierungsdatumFremdsystem'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'kuerzel_stornierungs_grund' => 'setKuerzelStornierungsGrund',
        'links' => 'setLinks',
        'stornierungsdatum_fremdsystem' => 'setStornierungsdatumFremdsystem'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'kuerzel_stornierungs_grund' => 'getKuerzelStornierungsGrund',
        'links' => 'getLinks',
        'stornierungsdatum_fremdsystem' => 'getStornierungsdatumFremdsystem'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['kuerzel_stornierungs_grund'] = isset($data['kuerzel_stornierungs_grund']) ? $data['kuerzel_stornierungs_grund'] : null;
        $this->container['links'] = isset($data['links']) ? $data['links'] : null;
        $this->container['stornierungsdatum_fremdsystem'] = isset($data['stornierungsdatum_fremdsystem']) ? $data['stornierungsdatum_fremdsystem'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets kuerzel_stornierungs_grund
     *
     * @return string
     */
    public function getKuerzelStornierungsGrund()
    {
        return $this->container['kuerzel_stornierungs_grund'];
    }

    /**
     * Sets kuerzel_stornierungs_grund
     *
     * @param string $kuerzel_stornierungs_grund Ein Kürzel aus der Bildungsmanager-Tabelle Teilnehmerstornierungsgründe. Je nach Kürzel wird dann der dazu passende Teilnehmerstornierungsgrund gesetzt. Wird kein Teilnehmerstornierungsgrund gesetzt, so greift der in den Systemeinstellungen der REST-Schnittstelle hinterlegte Standardgrund. Ist hier nichts hinterlegt, kann nicht storniert werden.
     *
     * @return $this
     */
    public function setKuerzelStornierungsGrund($kuerzel_stornierungs_grund)
    {
        $this->container['kuerzel_stornierungs_grund'] = $kuerzel_stornierungs_grund;

        return $this;
    }

    /**
     * Gets links
     *
     * @return \Swagger\Client\Model\Link[]
     */
    public function getLinks()
    {
        return $this->container['links'];
    }

    /**
     * Sets links
     *
     * @param \Swagger\Client\Model\Link[] $links links
     *
     * @return $this
     */
    public function setLinks($links)
    {
        $this->container['links'] = $links;

        return $this;
    }

    /**
     * Gets stornierungsdatum_fremdsystem
     *
     * @return \DateTime
     */
    public function getStornierungsdatumFremdsystem()
    {
        return $this->container['stornierungsdatum_fremdsystem'];
    }

    /**
     * Sets stornierungsdatum_fremdsystem
     *
     * @param \DateTime $stornierungsdatum_fremdsystem Stornierungsdatum des aufrufenden Systems. Wird nichts gesetzt, wird mit dem aktuellen Tagesdatum des Bildungsmanager-Servers vorbelegt.
     *
     * @return $this
     */
    public function setStornierungsdatumFremdsystem($stornierungsdatum_fremdsystem)
    {
        $this->container['stornierungsdatum_fremdsystem'] = $stornierungsdatum_fremdsystem;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


